image:
  repository: acrfordevopspoc01adrian.azurecr.io/devops-project
<<<<<<< HEAD
  tag: "1.0.3"
=======
  tag: "1.0.3"   # tu pipeline podmienia SHA
>>>>>>> 096e143 (Run)
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"

env:
  SPRING_PROFILES_ACTIVE: "dev"
  JAVA_OPTS: "-Xms128m -Xmx256m"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

