apiVersion: v1
kind: Service
metadata:
  name: adrian-java-app
  labels:
    app: adrian-java-app
spec:
  selector:
    app: adrian-java-app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
